Traceback (most recent call last):
  File "/Users/21ceo/opt/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/21ceo/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/21ceo/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/21ceo/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/21ceo/opt/anaconda3/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/21ceo/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/21ceo/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/21ceo/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Ignore the warnings
import warnings
warnings.filterwarnings('always')
warnings.filterwarnings('ignore')

# System related and data input controls
import os

# Data manipulation, visualization and useful functions
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format
pd.options.display.max_rows = 50
pd.options.display.max_columns = 40
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns

# Modeling algorithms
# General(Statistics/Econometrics)
from sklearn import preprocessing
import statsmodels.api as sm
import statsmodels.tsa.api as smt
import statsmodels.formula.api as smf
from statsmodels.stats.outliers_influence import variance_inflation_factor
from scipy import stats

# Regression
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.kernel_ridge import KernelRidge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, BaggingRegressor, GradientBoostingRegressor, AdaBoostRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

# Classification
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC, SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# Model selection
from sklearn.model_selection import train_test_split,cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

# Evaluation metrics
# for regression
from sklearn.metrics import mean_squared_log_error, mean_squared_error,  r2_score, mean_absolute_error
# for classification
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mXGBoostError[0m                              Traceback (most recent call last)
[0;32m<ipython-input-2-beb30023c678>[0m in [0;36m<module>[0;34m[0m
[1;32m     33[0m [0;32mfrom[0m [0msklearn[0m[0;34m.[0m[0mtree[0m [0;32mimport[0m [0mDecisionTreeRegressor[0m[0;34m[0m[0;34m[0m[0m
[1;32m     34[0m [0;32mfrom[0m [0msklearn[0m[0;34m.[0m[0mensemble[0m [0;32mimport[0m [0mRandomForestRegressor[0m[0;34m,[0m [0mBaggingRegressor[0m[0;34m,[0m [0mGradientBoostingRegressor[0m[0;34m,[0m [0mAdaBoostRegressor[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 35[0;31m [0;32mfrom[0m [0mxgboost[0m [0;32mimport[0m [0mXGBRegressor[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     36[0m [0;32mfrom[0m [0mlightgbm[0m [0;32mimport[0m [0mLGBMRegressor[0m[0;34m[0m[0;34m[0m[0m
[1;32m     37[0m [0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/xgboost/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0;32mimport[0m [0mos[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0;34m[0m[0m
[0;32m----> 9[0;31m [0;32mfrom[0m [0;34m.[0m[0mcore[0m [0;32mimport[0m [0mDMatrix[0m[0;34m,[0m [0mDeviceQuantileDMatrix[0m[0;34m,[0m [0mBooster[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m [0;32mfrom[0m [0;34m.[0m[0mtraining[0m [0;32mimport[0m [0mtrain[0m[0;34m,[0m [0mcv[0m[0;34m[0m[0;34m[0m[0m
[1;32m     11[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mrabit[0m  [0;31m# noqa[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/xgboost/core.py[0m in [0;36m<module>[0;34m[0m
[1;32m    172[0m [0;34m[0m[0m
[1;32m    173[0m [0;31m# load the XGBoost library globally[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 174[0;31m [0m_LIB[0m [0;34m=[0m [0m_load_lib[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    175[0m [0;34m[0m[0m
[1;32m    176[0m [0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/xgboost/core.py[0m in [0;36m_load_lib[0;34m()[0m
[1;32m    163[0m             [0;34m'`brew install libomp` to install OpenMP runtime.\n'[0m [0;34m+[0m[0;34m[0m[0;34m[0m[0m
[1;32m    164[0m             [0;34m'  * You are running 32-bit Python on a 64-bit OS\n'[0m [0;34m+[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 165[0;31m             'Error message(s): {}\n'.format(os_error_list))
[0m[1;32m    166[0m     [0mlib[0m[0;34m.[0m[0mXGBGetLastError[0m[0;34m.[0m[0mrestype[0m [0;34m=[0m [0mctypes[0m[0;34m.[0m[0mc_char_p[0m[0;34m[0m[0;34m[0m[0m
[1;32m    167[0m     [0mlib[0m[0;34m.[0m[0mcallback[0m [0;34m=[0m [0m_get_log_callback_func[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mXGBoostError[0m: XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libomp.dylib for Mac OSX, libgomp.so for Linux and other UNIX-like OSes). Mac OSX users: Run `brew install libomp` to install OpenMP runtime.
  * You are running 32-bit Python on a 64-bit OS
Error message(s): ['dlopen(/Users/21ceo/opt/anaconda3/lib/python3.7/site-packages/xgboost/lib/libxgboost.dylib, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n  Referenced from: /Users/21ceo/opt/anaconda3/lib/python3.7/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: image not found']

XGBoostError: XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libomp.dylib for Mac OSX, libgomp.so for Linux and other UNIX-like OSes). Mac OSX users: Run `brew install libomp` to install OpenMP runtime.
  * You are running 32-bit Python on a 64-bit OS
Error message(s): ['dlopen(/Users/21ceo/opt/anaconda3/lib/python3.7/site-packages/xgboost/lib/libxgboost.dylib, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n  Referenced from: /Users/21ceo/opt/anaconda3/lib/python3.7/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: image not found']


